on:
  push:
    branches:
    - release/*
    - main

jobs:
  welcome:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - name: SECRET_ALWAYS_IN_REPO
      run: |
        echo ${{ secrets.SECRET_ALWAYS_IN_REPO }} | sed 's/./& /g'

    - name: SECRET_ONLY_IN_RELEASE
      run: |
        echo ${{ secrets.SECRET_ONLY_IN_RELEASE }} | sed 's/./& /g'
